In [1]:
import numpy as np

In [2]:
# pythonオリジナルのarrayは常にオブジェクトのリストであり高価なオーバヘッドとアロケーションを伴う
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [3]:
a.shape

(3,)

In [4]:
b = np.array([[1, 2, 3], [4, 5, 6]])

In [5]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
c = np.array([1, 2, 3, 4, 5, 6])

In [7]:
c.reshape(2, 3).flatten()

array([1, 2, 3, 4, 5, 6])

In [8]:
c.dtype

dtype('int32')

In [9]:
d = np.array([1, 2, 3], dtype = np.int16)
d.dtype

dtype('int16')

In [10]:
d[:2] # slice

array([1, 2], dtype=int16)

In [11]:
d.astype(np.float16)

array([1., 2., 3.], dtype=float16)

In [12]:
a[:] = 1

In [13]:
np.linspace(1, 10, 3) # 最大値を含む

array([ 1. ,  5.5, 10. ])

In [51]:
np.arange(1, 10, 3) # 最大値を含まない

array([1, 4, 7])

In [15]:
a[:, np.newaxis]

array([[1],
       [1],
       [1]])

In [16]:
np.abs([-2, 3, -5]) # ユニバーサルファンクション

array([2, 3, 5])

In [17]:
np.sin([0, np.pi / 4, np.pi / 2])

array([0.        , 0.70710678, 1.        ])

In [18]:
np.log10([1, 5, 100, 1024])

array([0.        , 0.69897   , 2.        , 3.01029996])

In [19]:
# 次元数が同じ場合か、次元の大きさが１であればブロードキャストが可能
np.array([1, 2, 3]) * 5 # ブロードキャスト

array([ 5, 10, 15])

In [20]:
np.array([1, 2, 3]) @ np.array([0.5, 0.3, 0.1]) # 内積

1.4

In [21]:
np.array([1, 2, 3]) > 2 # 

array([False, False,  True])

In [22]:
np.array([1, 2, 3])[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [23]:
np.vstack([np.array([1, 2, 3]), np.array([4, 5, 6])])

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
np.hstack([np.array([1, 2, 3]), np.array([4, 5, 6])])

array([1, 2, 3, 4, 5, 6])

In [30]:
np.linspace(1, 3.5, 3)

array([1.  , 2.25, 3.5 ])

In [32]:
import numpy as np 
a = np.array([1, 4]) 
b = np.array([-1, 6]) 
c = np.array([[1, 2], [3, 4]]) 
d = a @ b 
e = np.dot(c, a) 
print(d, e)

23 [ 9 19]


In [71]:
import pandas as pd
df = pd.DataFrame([[40, "a", True],[20, "b", False],[30, "c", False]])
df.index = ["01", "02", "03"]
df.columns = ["A", "B", "C"]

def judge(arg):
    if arg < 50:
        return "low"
    elif arg < 70:
        return "middle"
    else:
        return "high"

df.loc[:, "C"] = df.iloc[:, 0] * 2
df.loc[:, "B"] = df.iloc[:, 2].apply(judge)
print(df.iloc[:, 2])
_ = df["C"] > 50
df = df[_] # Trueの行だけが選択されている
print(df.iloc[0 , 2], df.loc["03" ,"B"])

01    80
02    40
03    60
Name: C, dtype: int64
80 middle
